

	include(GNUInstallDirs)

	install(
		DIRECTORY ${PROJECT_SOURCE_DIR}/src/carl/
		DESTINATION ${CARL_INCLUDE_INSTALL_DIR}/carl
		FILES_MATCHING REGEX ".*\.(h|tpp)$"
	)

	install(
		TARGETS lib_carl
		EXPORT carl_Targets
		RUNTIME DESTINATION ${CARL_BIN_INSTALL_DIR}
		LIBRARY DESTINATION ${CARL_LIB_INSTALL_DIR}
		ARCHIVE DESTINATION ${CARL_LIB_INSTALL_DIR}
	)

	if(BUILD_STATIC)
		install(
			TARGETS lib_carl_static
			RUNTIME DESTINATION ${CARL_BIN_INSTALL_DIR}
			LIBRARY DESTINATION ${CARL_LIB_INSTALL_DIR}
			ARCHIVE DESTINATION ${CARL_LIB_INSTALL_DIR}
		)
	endif()

	install(FILES ${PROJECT_BINARY_DIR}/carlConfig.install.cmake DESTINATION ${CARL_CMAKE_INSTALL_DIR} RENAME carlConfig.cmake)
	install(FILES ${PROJECT_BINARY_DIR}/carlConfigVersion.cmake DESTINATION ${CARL_CMAKE_INSTALL_DIR})
	install(EXPORT carl_Targets FILE carlTargets.cmake DESTINATION ${CARL_CMAKE_INSTALL_DIR})

