name: Release new version
# Triggered by new a release on Github
# Deploys Docker containers and updates stable branch

on:
  release:
    types: [published]

jobs:
  deploy_docker:
    uses: ./.github/workflows/release_docker.yml
    with:
      # Use the tag from the release
      tag: ${{ github.event.release.tag_name }}

  update_stable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git clone
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
      - name: Rebase
        run: |
          git config user.name 'Stormchecker bot'
          git config user.email 'dev@stormchecker.org'
          git fetch origin stable
          git checkout stable
          git rebase ${{ github.event.release.tag_name }}
          git push origin stable

  deploy_docker_stable:
    needs: update_stable
    uses: ./.github/workflows/release_docker.yml
    with:
      tag: stable
